# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doordash', '0002_auto_20170525_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_new_customer_renamed',
            field=models.BooleanField(default=True),
        ),
    ]
