# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doordash', '0003_customer_is_new_customer_renamed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemrelationship',
            name='special_instructions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitemrelationship',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
