# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:15
from __future__ import unicode_literals

from django.db import migrations


def set_default_values(apps, schema_editor):
    # We can't import the OrderItemRelationship model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OrderItemRelationship = apps.get_model('doordash', 'OrderItemRelationship')
    for order_item in OrderItemRelationship.objects.all():
        order_item.special_instructions = "n/a"
        order_item.subtotal = 0
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doordash', '0004_auto_20170525_1825'),
    ]

    operations = [
        migrations.RunPython(set_default_values),
    ]
