# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doordash', '0005_auto_20170525_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemrelationship',
            name='special_instructions',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitemrelationship',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
